inherit_from: .rubocop_todo.yml

AllCops:
  Exclude:
    - config/initializers/forbidden_yaml.rb
    - !ruby/regexp /(vendor|bundle|bin|db)\/.*/
  RunRailsCops: true
  DisplayCopNames: true
  DisplayStyleGuide: true

Metrics/CyclomaticComplexity:
  Max: 9 # TODO: Lower to 6

Metrics/LineLength:
  Max: 100 # TODO: Lower to 80

Metrics/PerceivedComplexity:
  Max: 10 # TODO: Lower to 7

Style/AlignParameters:
  EnforcedStyle: with_fixed_indentation

Style/ClassAndModuleChildren:
  EnforcedStyle: compact

Style/Documentation:
  Enabled: false

Style/MultilineOperationIndentation:
  EnforcedStyle: indented
