inherit_from: .rubocop_todo.yml

AllCops:
  Exclude:
    - config/initializers/forbidden_yaml.rb
    - !ruby/regexp /(vendor|bundle|bin|db)\/.*/
  RunRailsCops: true
  DisplayCopNames: true
  DisplayStyleGuide: true

Metrics/PerceivedComplexity:
  Max: 10 # TODO: Lower to 7

Metrics/CyclomaticComplexity:
  Max: 9 # TODO: Lower to 6

Style/ClassAndModuleChildren:
  EnforcedStyle: compact

Style/Documentation:
  Enabled: false
