development:
  host: localhost
  s3_bucket: ""

test:
  host: localhost
  s3_bucket: test.s3.rubygems.org

staging:
  host: staging.rubygems.org
  s3_bucket: staging.s3.rubygems.org

live: &LIVE
  host: rubygems.org
  s3_bucket: production.s3.rubygems.org

production:
  <<: *LIVE

recovery:
  <<: *LIVE
